add new script with pkce support

diff --git a/scripts/kubectl-login b/scripts/kubectl-login
--- a/scripts/kubectl-login
+++ b/scripts/kubectl-login
@@ -5,13 +5,14 @@ CLUSTER=$3
 KEYCLOAK_URL=https://sso.clastix.io
 KEYCLOAK_REALM=caas
 KEYCLOAK_CLIENT_ID=kubernetes
-KEYCLOAK_CLIENT_SECRET=f5268c5d-46df-45f8-852d-8b2a85d72d69
+KEYCLOAK_CLIENT_SECRET=*******
 
 # Check if jq is installed
 if [ ! -x "$(command -v jq)" ]; then
     echo "Error: jq not found"
     exit 1
 fi
+
 
 # Check if curl is installed
 if [ ! -x "$(command -v curl)" ]; then
@@ -24,11 +25,11 @@ if [ "${CLUSTER}" = "" ];then
 fi
 
 if [ "${USERNAME}" = "" ];then
-	read -p "username: " USERNAME
+        read -p "username: " USERNAME
 fi
 
 if [ "${PASSWORD}" = "" ];then
-	read -sp "password: " PASSWORD
+        read -sp "password: " PASSWORD
 fi
 
 
@@ -40,7 +41,7 @@ echo "# Getting a token ..."
 TOKEN=`curl -k -s ${KEYCLOAK_TOKEN_URL} \
   -d grant_type=password \
   -d response_type=id_token \
-  -d scope=openid \
+  -d scope="openid website" \
   -d client_id=${KEYCLOAK_CLIENT_ID} \
   -d client_secret=${KEYCLOAK_CLIENT_SECRET} \
   -d username=${USERNAME} \
@@ -48,25 +49,38 @@ TOKEN=`curl -k -s ${KEYCLOAK_TOKEN_URL} \
 
 RET=$?
 if [ "$RET" != "0" ];then
-	echo "# Error ($RET) ==> ${TOKEN}";
-	exit ${RET}
+        echo "# Error ($RET) ==> ${TOKEN}";
+        exit ${RET}
 fi
 
 ERROR=`echo ${TOKEN} | jq .error -r`
 if [ "${ERROR}" != "null" ];then
-	echo "# Failed ==> ${TOKEN}" >&2
-	exit 1
+        echo "# Failed ==> ${TOKEN}" >&2
+        exit 1
 fi
 
 ID_TOKEN=`echo ${TOKEN} | jq .id_token -r`
+ACCESS_TOKEN=`echo ${TOKEN} | jq .access_token -r`
 REFRESH_TOKEN=`echo ${TOKEN} | jq .refresh_token -r`
 
-echo "id_token:" ${ID_TOKEN}
+echo
+echo "got the access_token:"
+curl -s -k --user ${KEYCLOAK_CLIENT_ID}:${KEYCLOAK_CLIENT_SECRET} \
+    -d token=${ACCESS_TOKEN} ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token/introspect | jq
 
-
-echo "introspect the token:"
-curl -k --user ${KEYCLOAK_CLIENT_ID}:${KEYCLOAK_CLIENT_SECRET} \
+echo
+echo "got the id_token:"
+curl -s -k --user ${KEYCLOAK_CLIENT_ID}:${KEYCLOAK_CLIENT_SECRET} \
     -d token=${ID_TOKEN} ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token/introspect | jq
+echo
+
+echo "got the refresh_token:"
+curl -s -k --user ${KEYCLOAK_CLIENT_ID}:${KEYCLOAK_CLIENT_SECRET} \
+    -d token=${REFRESH_TOKEN} ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token/introspect | jq
+echo
+
+echo "user info:"
+curl -s -k -d access_token=${ACCESS_TOKEN} ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo | jq
 
 # Create the kubeconfig file
 cat > ${USERNAME}-oidc.kubeconfig <<EOF
@@ -95,10 +109,9 @@ users:
         id-token: ${ID_TOKEN}
         idp-issuer-url: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}
         refresh-token: ${REFRESH_TOKEN}
+        idp-certificate-authority: rootCA.crt
       name: oidc
 EOF
 
 echo "kubeconfig file is:" ${USERNAME}-oidc.kubeconfig
 echo "to use it as" ${USERNAME} "export KUBECONFIG="${USERNAME}-oidc.kubeconfig
-echo "Warning: the refresh token will expire in 30 minutes!"
-
