further improvements

diff --git a/scripts/kubectl-oidc b/scripts/kubectl-oidc
--- a/scripts/kubectl-oidc
+++ b/scripts/kubectl-oidc
@@ -13,12 +13,6 @@
 set -e
 set -o pipefail
 
-BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-PATH=$PATH:$BIN_DIR
-CONFIG=~/.kube/oidc.conf
-CACHE=~/.kube/oidc.cache
-source "$CONFIG"
-
 check_prerequisites() {
     echo "[$(date)][INFO] Checking if prerequisites are installed"
 
@@ -71,7 +65,7 @@ get_openid_config() {
     USERINFO_ENDPOINT=`echo ${OPENID} | jq .userinfo_endpoint -r`
     END_SESSION_ENDPOINT=`echo ${OPENID} | jq .end_session_endpoint -r`
     GRANT_TYPES=`echo ${OPENID} | jq .grant_types_supported -r`
-    RESPONSE_TYPE=`echo ${OPENID} | jq .response_types_supported -r`
+    RESPONSE_TYPES=`echo ${OPENID} | jq .response_types_supported -r`
     RESPONSE_MODES=`echo ${OPENID} | jq .response_modes_supported -r`
     CLAIMS=`echo ${OPENID} | jq .claims_supported -r`
     SCOPES=`echo ${OPENID} | jq .scopes_supported -r`
@@ -83,7 +77,6 @@ save_config() {
 cat > $CONFIG <<EOF
 OIDC_SERVER=${OIDC_SERVER}
 OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
-OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
 PKCE=${PKCE}
 CODE_CHALLENGE_METHOD=${CODE_CHALLENGE_METHOD}
 REDIRECT_URI=${REDIRECT_URI}
@@ -94,8 +87,9 @@ USERINFO_ENDPOINT=${USERINFO_ENDPOINT}
 END_SESSION_ENDPOINT=${END_SESSION_ENDPOINT}
 EOF
 
+#OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
 #GRANT_TYPES=${GRANT_TYPES}
-#RESPONSE_TYPE=${RESPONSE_TYPE}
+#RESPONSE_TYPES=${RESPONSE_TYPES}
 #RESPONSE_MODES=${RESPONSE_MODES}
 #CLAIMS=${CLAIMS}
 #SCOPES=${SCOPES}
@@ -115,8 +109,24 @@ gen_pkce() {
 create_auth_uri() {
     echo "[$(date)][INFO] Creating authorization URI"
     STATE=`openssl rand -base64 32 | tr -dc A-Za-z0-9`
-    QUERY="response_type=code&client_id="${OIDC_CLIENT_ID}"&redirect_uri="${REDIRECT_URI}"&scope=openid+groups+offline_access&state="${STATE}"&code_challenge="${CODE_CHALLENGE}"&prompt=consent&code_challenge_method="${CODE_CHALLENGE_METHOD}"&access_type=offline"
-    AUTH_URI=${AUTH_ENDPOINT}?${QUERY}
+    RESPONSE_TYPE="code"
+    SCOPE="openid+groups+offline_access"
+    PROMPT="consent"
+    ACCESS_TYPE="offline"
+    
+    QUERY="?"
+    QUERY=$QUERY"response_type="$RESPONSE_TYPE"&"
+    QUERY=$QUERY"client_id="$OIDC_CLIENT_ID"&"
+    QUERY=$QUERY"redirect_uri="$REDIRECT_URI"&"
+    QUERY=$QUERY"scope="$SCOPE"&"
+    QUERY=$QUERY"state="$STATE"&"
+    QUERY=$QUERY"prompt="$PROMPT"&"
+    QUERY=$QUERY"code_challenge="$CODE_CHALLENGE"&"
+    QUERY=$QUERY"code_challenge_method="$CODE_CHALLENGE_METHOD"&"
+    QUERY=$QUERY"access_type="$ACCESS_TYPE
+
+    #QUERY="response_type=code&client_id="${OIDC_CLIENT_ID}"&redirect_uri="${REDIRECT_URI}"&scope=openid+groups+offline_access&state="${STATE}"&code_challenge="${CODE_CHALLENGE}"&prompt=consent&code_challenge_method="${CODE_CHALLENGE_METHOD}"&access_type=offline"
+    AUTH_URI=${AUTH_ENDPOINT}${QUERY}
     echo
     echo "Go to the following link in your browser:"
     echo
@@ -132,11 +142,15 @@ get_code() {
 get_token() {
     echo "[$(date)][INFO] Requesting token from $OIDC_SERVER"
 
+    # For public OIDC clients, the OIDC_CLIENT_SECRET is not required
+    # We should set a configuration option to distinguish if
+    # the OIDC_CLIENT_SECRET is necessary (confidential client) or not (public client)
+    # -d client_secret=$OIDC_CLIENT_SECRET
+    
     TOKEN=`curl -k -s $TOKEN_ENDPOINT \
     -d grant_type=authorization_code \
     -d response_type=id_token \
     -d client_id=$OIDC_CLIENT_ID \
-    -d client_secret=$OIDC_CLIENT_SECRET \
     -d code=$CODE \
     -d code_verifier=$CODE_VERIFIER \
     -d redirect_uri=$REDIRECT_URI`
@@ -229,8 +243,7 @@ token() {
             TOKEN=`curl -k -s $TOKEN_ENDPOINT \
             -d grant_type=refresh_token \
             -d refresh_token=${REFRESH_TOKEN} \
-            -d client_id=${OIDC_CLIENT_ID} \
-            -d client_secret=${OIDC_CLIENT_SECRET}`
+            -d client_id=${OIDC_CLIENT_ID}`
 
             ERROR=$(echo "$TOKEN" | jq .error -r)
             if [ "$ERROR" != "null" ]; then
@@ -288,4 +301,16 @@ main() {
     exit 1
 }
 
-main "$@"
+
+BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PATH=$PATH:$BIN_DIR
+CONFIG=~/.kube/oidc.conf
+CACHE=~/.kube/oidc.cache
+
+if [ -r "$CONFIG" ]; then
+    source "$CONFIG"
+    main "$@"
+else
+    echo "[$(date)][ERROR]  Missing configuration." >&2
+    exit 1
+fi
